name: Deploy to demoland

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Build and upload
    runs-on: ubuntu-latest
    environment: demoland
    env:
      NODE_ENV: production
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: "*"

      - uses: pnpm/action-setup@v2
        with:
          version: 8
          run_install: false

      - name: Get pnpm store directory
        id: pnpm-cache
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path)" >> $GITHUB_OUTPUT

      - name: Setup pnpm cache
        uses: actions/cache@v3
        with:
          path: ${{ steps.pnpm-cache.outputs.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - run: pnpm install --ignore-scripts
        env:
          NODE_ENV: development

      - run: pnpm run build

      - name: SCP upload
        uses: appleboy/scp-action@master
        with:
          host: "demo.land"
          username: ${{ vars.USER }}
          password: ${{ secrets.PASS }}
          port: 22
          source: "dist/*,dist/**/*"
          target: ${{ vars.TARGET_PATH }}
