name: Test & Lint

on: push

jobs:
  test:
    name: From build to lint
    runs-on: ubuntu-latest
    env:
      NODE_ENV: development
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: "*"

      - uses: pnpm/action-setup@v2
        with:
          version: 8
          run_install: |
            - args: [--ignore-scripts]

      - run: pnpm run build

      - run: pnpm test

      - run: pnpm run lint
