name: Lint & Test

on: push

jobs:
  test:
    name: From build to publish
    runs-on: ubuntu-latest
    env:
      NODE_ENV: development
      NPM_TOKEN: "${{ secrets.NPM_TOKEN }}"
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: "*"

      - uses: pnpm/action-setup@v2
        env:
          NODE_ENV: development
        with:
          version: latest
          run_install: |
            - args: [--ignore-scripts]

      - run: pnpm run build

      - run: pnpm publish --dry-run --no-git-checks

      - run: pnpm test

      - run: pnpm run lint
